// GENERATED by Packages/WebTypes (agents-webtypes) from AgentsKitCore. Do not edit.
// Regenerate: scripts/web.sh types
//
// Read from DaemonAPI*.swift, DaemonAPI+Control.swift, Grant.swift, ControlAuth.swift
// and Model/, in Packages/AgentsKit/Sources/AgentsKitCore.

export {};
