// GENERATED by Packages/WebTypes (agents-webtypes) from AgentsKitCore. Do not edit.
// Regenerate: scripts/web.sh types
//
// Every type a method in DaemonAPI.WebSignatures reaches, read from the Swift source of
// Packages/AgentsKit/Sources/AgentsKitCore. Hand-written shapes come from
// Packages/WebTypes/Overrides. contracts/generated-types.md in specs/071-web-remote says how.

/** Any JSON: JSONValue in Swift. */
export type JSONValue = null | boolean | number | string | JSONValue[] | { [key: string]: JSONValue };
/** Upper case, as Swift's uuidString writes it. */
export type UUID = string & { readonly __brand: "UUID" };
/** Standard base64, with padding: Data in Swift. */
export type Base64 = string & { readonly __brand: "Base64" };
/** Seconds since 2001-01-01T00:00:00Z: Date in Swift, through a plain JSONEncoder. */
export type WireDate = number & { readonly __brand: "WireDate" };
/** An absolute URL as text: URL in Swift. */
export type URLString = string & { readonly __brand: "URLString" };

/** DaemonAPI.Failure: the codes a call can fail with. */
export const Failure = {
  agentLimitReached: -32023,
  busy: -32040,
  catalogRefused: -32080,
  changedElsewhere: -32093,
  cloneFailed: -32026,
  couldNotSave: -32095,
  credentialWanted: -32036,
  dayLimitReached: -32018,
  deleteRefused: -32051,
  eventRefused: -32050,
  fileGone: -32032,
  fileNotReadable: -32033,
  folderGone: -32004,
  folderInTheWay: -32025,
  hostOffline: -32090,
  importedAgent: -32096,
  lastOperator: -32092,
  leaseRefused: -32035,
  needsSignIn: -32007,
  noSuchAgent: -32005,
  noSuchHost: -32091,
  noSuchProject: -32012,
  noSuchWorkflow: -32014,
  noWait: -32051,
  notACloneURL: -32024,
  notAServer: -32038,
  notASurface: -32022,
  notAWorktree: -32030,
  notAllowed: -32060,
  notChanged: -32034,
  notConfirmed: -32010,
  notInWorkflowFolder: -32016,
  notOffered: -32039,
  notPermitted: -32045,
  notSupported: -32009,
  notYours: -32027,
  outsideScratchRoot: -32098,
  pinRefused: -32061,
  projectHasLiveAgents: -32013,
  runtimeNotFound: -32001,
  runtimeWillNotStart: -32002,
  sandboxWillNotStart: -32061,
  sessionGone: -32003,
  sessionLiveElsewhere: -32097,
  shellNotLive: -32011,
  shellWillNotStart: -32010,
  signInWanted: -32070,
  storeUnavailable: -32094,
  viewNeedsShow: -32063,
  viewRefused: -32062,
  workflowLimitReached: -32017,
  workflowTurnedOffByPerson: -32041,
  workflowUnreadable: -32015,
  worktreeFailed: -32028,
  worktreeInUse: -32031,
  worktreeMissing: -32029,
  wrongProtocolVersion: -32008,
} as const;

export interface ACPAuthMethod {
  id: string;
  name?: string;
  description?: string;
  _meta?: JSONValue;
}

export interface ACPPromptCapabilities {
  image?: boolean;
  audio?: boolean;
  embeddedContext?: boolean;
}

export interface ACPProviderInfo {
  id: string;
  name?: string;
  protocol?: string;
  configured?: boolean;
}

export type AfterTurn = "park" | "archive";

export interface Agent {
  id: UUID;
  runtimeID: string;
  cwd: URLString;
  title?: string;
  labels?: SessionLabel[];
  state: AgentState;
  runtimeSessionID?: string;
  startOptions: StartOptions;
  advertisedOptions: ConfigOption[];
  availableCommands: SlashCommand[];
  createdAt: WireDate;
  lastActivityAt: WireDate;
  isUnread?: boolean;
  reportSeenAt?: WireDate;
  endedReason?: EndedReason;
  archivedReason?: AgentArchivedReason;
  usage?: Usage;
  lastTurnUsage?: TurnUsage;
  costToDate?: Record<string, number>;
  costCeiling?: Cost;
  plans?: Plan[];
  background?: BackgroundItem[];
  additionalDirectories?: URLString[];
  mcpServers?: MCPServer[];
  queuedPrompts?: QueuedPrompt[];
  suggestedPrompts?: SuggestedPrompt[];
  startedByWorkflow?: string;
  startedByRun?: UUID;
  startedByAgent?: UUID;
  chainDepth?: number;
  eventWait?: EventWait;
  worktree?: AgentWorktree;
  pendingMove?: PendingMove;
  startingPoint?: StartingPoint;
  startRequestID?: UUID;
  restartPickUps?: number;
  report?: WorkReport;
  outcomeAsked?: boolean;
  titledByAgent?: boolean;
  parking?: Parking;
  afterTurn?: AfterTurn;
  archivedAt?: WireDate;
  sandboxOverride?: SandboxChoice;
  effectiveSandbox?: EffectiveSandbox;
  pendingSandboxFailure?: SandboxFailureRecord;
  missingFolder?: MissingFolder;
  listsLeftOut?: boolean;
  madeInRoot?: string;
  queuedStart?: QueuedStart;
}

export type AgentArchivedReason = "byUser" | "byAgent";

export type AgentGroup = "needsAttention" | "blocked" | "waiting" | "running" | "finished" | "stopped" | "parked" | "archived";

export interface AgentRemovedNotification {
  agentID: UUID;
}

export interface AgentRequest {
  agentID: UUID;
}

export type AgentState = "starting" | "running" | "waitingOnUser" | "finished" | "stopped" | "archived" | "queued";

export interface AgentWorktree {
  name: string;
  root: URLString;
  branch?: string;
  project: URLString;
  base?: string;
  madeByApp: boolean;
}

export interface AllowanceReading {
  window?: string;
  used?: number;
  resetsAt?: WireDate;
  spent: boolean;
  nearlySpent: boolean;
  at: WireDate;
}

export interface AllowanceState {
  credentialKey: string;
  entryID: UUID;
  status: AllowanceStateStatus;
  since: WireDate;
  changedAt: WireDate;
  learnedFrom: AllowanceStateSource;
  lastRateLimit?: RateLimitInfo;
  reading?: AllowanceReading;
  spent: AllowanceStateSpent;
  rateLimitStreak: WireDate[];
  modelsOut?: AllowanceStateModelOut[];
}

export interface AllowanceStateModelOut {
  model: string;
  name?: string;
  since: WireDate;
  retryAfter: WireDate;
}

export type AllowanceStateOutReason = "allowanceSpent" | "overage" | "creditUsedUp" | "creditExpired" | "rateLimitPersisted" | "runtimeFailed";

export type AllowanceStateSource = "typedFailure" | "words" | "overageReport" | "ledger" | "expiry" | "person" | "runtimeFailure";

export type AllowanceStateSpent =
  | { known: { _0?: Cost } }
  | { unknown: Record<string, never> };

export type AllowanceStateStatus =
  | { available: Record<string, never> }
  | { rateLimited: { until: WireDate } }
  | { out: { until?: WireDate; retryAfter?: WireDate; why: AllowanceStateOutReason } };

export interface AnswerElicitationRequest {
  requestID: UUID;
  action: AnswerElicitationRequestAction;
  content: Record<string, JSONValue>;
  sendID?: UUID;
}

export type AnswerElicitationRequestAction = "accept" | "decline" | "cancel";

export interface AnswerRequest {
  permissionID: UUID;
  optionID: string;
  sendID?: UUID;
}

export interface AnswerSandboxRequest {
  agentID: UUID;
  carryOn: boolean;
}

export interface AppViewCall {
  id: UUID;
  server: string;
  tool: string;
  resourceUri: string;
  arguments?: JSONValue;
  result?: JSONValue;
  state: AppViewCallState;
  reason?: string;
  pinnable?: boolean;
}

export type AppViewCallState = "running" | "done" | "cancelled";

export interface AppViewPolicy {
  connectDomains: string[];
  resourceDomains: string[];
  frameDomains: string[];
  baseUriDomains: string[];
  refused: string[];
}

export interface ArtifactWriteRequest {
  agentID: UUID;
  path: string;
  text: string;
}

export interface Attachment {
  id: UUID;
  block: ContentBlock;
  displayName: string;
  byteCount?: number;
}

export interface AttentionDelivery {
  needID: NeedID;
  to?: Surface;
}

export interface AttentionNotification {
  needID: NeedID;
  need?: Need;
  to?: Surface;
  alert: boolean;
}

export interface AttentionPending {
  needs: Need[];
  deliveries: AttentionDelivery[];
}

export interface AuthStatus {
  kind: string;
  label: string;
}

export interface BackgroundItem {
  id: string;
  kind: BackgroundItemKind;
  name: string;
  taskType?: string;
  detail?: string;
  command?: string;
  state: BackgroundItemState;
  canStop: boolean;
  isStopping: boolean;
  parentID?: string;
  toolCallID?: string;
  outputFilePath?: string;
  summary?: string;
  lastToolName?: string;
  startedAt: WireDate;
  endedAt?: WireDate;
}

export type BackgroundItemKind = "task" | "subagent";

export type BackgroundItemState = "running" | "paused" | "completed" | "failed" | "stopped" | "disconnected";

export interface Block {
  waits: Wait[];
  checkAgainAt?: WireDate;
  wakeOn?: BlockWakeOn;
  clearedAt?: WireDate;
  clearedBy?: BlockClearing;
}

export type BlockClearing = "waits" | "time" | "dropped";

export type BlockWakeOn = "any" | "all";

export interface BranchSummary {
  name: string;
  remote?: string;
}

export interface CarriedSetting {
  optionID: string;
  name: string;
  from?: JSONValue;
  to?: JSONValue;
  source: CarriedSettingSource;
}

export type CarriedSettingSource =
  | { level: { _0: string } }
  | { sameValue: Record<string, never> }
  | { poolEntry: Record<string, never> }
  | { remembered: Record<string, never> }
  | { runtimeDefault: Record<string, never> }
  | { strictestMode: Record<string, never> }
  | { closestNoLooser: Record<string, never> }
  | { person: Record<string, never> };

export type ChangeSource = "reported" | "reportedAndSeen" | "seen";

export type ChangeState = "modified" | "added" | "deleted" | "binary" | "renamed" | "untracked";

export interface ChangedFile {
  path: string;
  relativePath?: string;
  source: ChangeSource;
  state: ChangeState;
  editCount: number;
  added?: number;
  removed?: number;
  beyondReported: boolean;
  inProgress: boolean;
  outsideFolder: boolean;
  firstLine?: number;
  oldPath?: string;
}

export interface ChangedFileDetail {
  file: ChangedFile;
  edits: ReportedEdit[];
  hunks?: FolderHunk[];
  whole?: DiffLine[];
}

export interface ChangesFileRequest {
  agentID: UUID;
  path: string;
  whole: boolean;
}

export interface ChangesList {
  files: ChangedFile[];
  git: GitView;
  reportsEdits: boolean;
  more?: number;
}

export interface ChangesListRequest {
  agentID: UUID;
}

export type ChangesUnavailable =
  | { notARepository: Record<string, never> }
  | { gitNotInstalled: Record<string, never> }
  | { folderGone: Record<string, never> }
  | { failed: { message: string } };

export type ChatProjectState =
  | { ready: { folder: URLString } }
  | { archived: { folder: URLString } }
  | { noPersonalHome: Record<string, never> }
  | { failed: { message: string } };

export interface CloneNotification {
  clone: CloneSummary;
  finished: boolean;
}

export interface CloneRequest {
  url: string;
}

export interface CloneSummary {
  id: UUID;
  url: string;
  folder: URLString;
  startedAt: WireDate;
}

export interface ConfigChoice {
  value: JSONValue;
  name: string;
  description?: string;
}

export interface ConfigChoiceGroup {
  name?: string;
  group?: string;
  options: ConfigChoice[];
}

// uses: ConfigChoice, ConfigChoiceGroup, JSONValue
/**
 * ConfigOption (Model/Options.swift), as its encode(to:) writes it: `type` is the kind's
 * wire name, and `options` is a flat list for one unnamed group, else the groups.
 */
export interface ConfigOption {
  id: string;
  name: string;
  description?: string;
  category?: string;
  /** "select", "boolean", or a kind this build doesn't know, carried as itself. */
  type: string;
  currentValue?: JSONValue;
  options?: ConfigChoice[] | ConfigChoiceGroup[];
}

export type Consequence =
  | { woke: { agentID: UUID; title: string } }
  | { fired: { workflowID: string; folder: URLString; agentID?: UUID } }
  | { refused: { workflowID: string; folder: URLString; reason: WorkflowRefusal } }
  | { couldNotWake: { agentID: UUID; title: string; reason: string } };

// uses: ContentBlock.Annotations
/**
 * ContentBlock (ACP/ContentBlock.swift): the protocol's own block shapes, as sent. A block of a
 * kind this build doesn't know is written back as it came, so any other `type` may arrive.
 */
export type ContentBlock =
  | { type: "text"; text: string }
  | { type: "image"; mimeType: string; data: string; uri?: string }
  | { type: "audio"; mimeType: string; data: string }
  | {
      type: "resource_link";
      uri: string;
      name: string;
      mimeType?: string;
      size?: number;
      annotations?: ContentBlockAnnotations;
    }
  | {
      type: "resource";
      resource: { uri: string; text?: string; blob?: string; mimeType?: string };
      annotations?: ContentBlockAnnotations;
    };

export interface ContentBlockAnnotations {
  audience?: string[];
  priority?: number;
}

export interface ContinueInProjectRequest {
  agentID: UUID;
  text: string;
  attachments: Attachment[];
  requestID?: UUID;
}

export interface ControlHost {
  id: HostID;
  name: string;
  platform: string;
  version: string;
  state: string;
  reach: string;
  machineID?: string;
  relay?: boolean;
  signInFrom?: Record<string, HostID>;
  tunnel?: HostTunnel;
}

export interface ControlStatus {
  name: string;
  version: string;
  homeHost?: HostID;
  machineID: string;
  startedAt?: WireDate;
  port?: number;
  awayFromHome?: boolean;
  you?: UUID;
  relayKey?: Base64;
  web?: WebRemoteStatus;
  thisMacHost?: HostJoinStatus;
  projectDetection?: ProjectDetection;
}

export interface Cost {
  amount: number;
  currency: string;
}

export interface CostLimits {
  perAgent?: Cost;
  daily?: Cost;
}

export interface CostState {
  limits: CostLimits;
  today: Record<string, number>;
  day: string;
  note?: string;
}

export type CredentialKind = "geminiAPIKey";

export interface CredentialsLend {
  runtime: string;
  kind: CredentialKind;
  secret: string;
}

export interface CredentialsOffer {
  runtimes: string[];
  ownSignInOnly: boolean;
  notRelayed?: Record<string, SignInWantedReason>;
  signIns?: string[];
}

export interface DeclaredResource {
  name: ResourceName;
  displayName: string;
  description: string;
  holders: number;
  defaultMinutes?: number;
  maximumMinutes?: number;
}

export type DeviceKind = "iPhone" | "iPad" | "unknown";

export interface DiffLine {
  kind: DiffLineKind;
  text: string;
  newLine?: number;
}

export type DiffLineKind = "context" | "added" | "removed";

export interface DirectoryEntry {
  url: URLString;
  name: string;
  isDirectory: boolean;
  size?: number;
  modifiedAt?: WireDate;
}

export interface DirectoryListing {
  url: URLString;
  entries: DirectoryEntry[];
  omitted: number;
}

export interface DiscardDraftRequest {
  draftID: UUID;
}

export interface DiskAlarm {
  reading: DiskReading;
  level: DiskLevel;
  threshold: number;
  worktrees: DiskWorktree[];
}

export type DiskLevel = "ok" | "low" | "critical";

export interface DiskReading {
  volume: string;
  mount: string;
  freeBytes: number;
  totalBytes: number;
}

export interface DiskState {
  alarms: DiskAlarm[];
}

export interface DiskThresholds {
  lowGB?: number;
  lowPercent?: number;
  criticalGB?: number;
}

export interface DiskWorktree {
  name: string;
  bytes: number;
  partial: boolean;
}

export interface DraftOptionsNotification {
  draftID: UUID;
  options: ConfigOption[];
  commands: SlashCommand[];
  failure?: string;
}

export interface DropboxPutRequest {
  folder: URLString;
  subfolder?: string;
  name: string;
  data: Base64;
}

export interface DropboxPutResponse {
  path: string;
}

export type Dropped =
  | { extraArguments: { _0: string[] } }
  | { alwaysAllow: { count: number } }
  | { queuedSlashCommand: { _0: string } };

export interface EffectiveSandbox {
  state: SandboxState;
  requested: SandboxChoice;
  reason?: string;
}

export interface ElicitationAnswer {
  question: string;
  answer: string;
}

export interface ElicitationNotification {
  agentID: UUID;
  requestID: UUID;
  request?: ElicitationRequest;
}

export interface ElicitationRequest {
  id: UUID;
  elicitationID?: string;
  agentID: UUID;
  message?: string;
  mode: ElicitationRequestMode;
  scope: ElicitationRequestScope;
  askedAt: WireDate;
}

export type ElicitationRequestMode =
  | { form: { _0: ElicitationSchema } }
  | { url: { _0: string } };

export type ElicitationRequestScope = "session" | "request";

export interface ElicitationSchema {
  title?: string;
  description?: string;
  properties: ElicitationSchemaProperty[];
}

export interface ElicitationSchemaProperty {
  name: string;
  title?: string;
  description?: string;
  isRequired: boolean;
  kind: ElicitationSchemaPropertyKind;
  defaultValue?: JSONValue;
}

export interface ElicitationSchemaPropertyChoice {
  value: string;
  title: string;
  description?: string;
}

export type ElicitationSchemaPropertyFormat = "email" | "uri" | "date" | "date-time";

export type ElicitationSchemaPropertyKind =
  | { string: { format?: ElicitationSchemaPropertyFormat; minLength?: number; maxLength?: number; choices?: ElicitationSchemaPropertyChoice[] } }
  | { number: { minimum?: number; maximum?: number } }
  | { integer: { minimum?: number; maximum?: number } }
  | { boolean: Record<string, never> }
  | { multiSelect: { items: ElicitationSchemaPropertyChoice[]; minItems?: number; maxItems?: number } };

export interface Empty {}

export type EndedReason = "endTurn" | "maxTokens" | "maxTurnRequests" | "refusal" | "cancelled" | "processDied" | "daemonGone" | "costLimit" | "unrecognised" | "stoppedByAgent" | "signInRefused" | "runtimeError" | "allowanceSpent" | "rateLimited" | "sandboxFailed" | "imported";

export interface EntryNotification {
  agentID: UUID;
  entry: TranscriptEntry;
  index?: number;
  oversized?: number;
}

export interface Event {
  position: number;
  name: string;
  at: WireDate;
  lastAt?: WireDate;
  count: number;
  scope: EventScope;
  sentence: string;
  details: Record<string, string>;
  publisher?: EventPublisher;
  message?: string;
  chainDepth: number;
  consequences: Consequence[];
}

export type EventGroup = "agents" | "workflows" | "branches" | "dropbox" | "mac" | "custom";

/**
 * EventPattern (Model/EventPattern.swift), as its encode(to:) writes it (073): `filters` holds
 * every filter as one string, a list joined by `|` so an older build reads it as a value that
 * never matches, and `anyOf` holds the lists whole. Read `anyOf` over `filters`.
 */
export interface EventPattern {
  name: string;
  filters: Record<string, string>;
  anyOf?: Record<string, string[]>;
}

export interface EventPublisher {
  agentID: UUID;
  title: string;
}

export type EventScope =
  | { mac: Record<string, never> }
  | { project: { _0: URLString } };

export interface EventWait {
  id: UUID;
  patterns: EventPattern[];
  from: number;
  deadline?: WireDate;
  since: WireDate;
  ending?: EventWaitEnding;
  resumePromptID?: UUID;
}

export type EventWaitEnding =
  | { matched: { position: number; extraMatches: number } }
  | { timedOut: Record<string, never> }
  | { cancelled: { by: EventWaitEndingCanceller } }
  | { couldNotWake: { reason: string } };

export type EventWaitEndingCanceller = "agent" | "person" | "prompt" | "stopped" | "archived";

export interface EventsListRequest {
  before?: number;
  limit: number;
  scope?: EventScope;
  groups?: EventGroup[];
}

export interface EventsPage {
  events: Event[];
  waiting: WaitingAgent[];
  hasMore: boolean;
}

export interface FileMentionDTO {
  path: string;
  relativePath: string;
}

export interface FileMentionRequest {
  agentID: UUID;
  term: string;
}

// uses: FileStamp
/** FileReading (Model/FileReading.swift), as its encode(to:) writes it: one shape per `kind`. */
export type FileReading =
  | { kind: "text"; stamp: FileStamp; text: string; isTruncated: boolean; size: number }
  | { kind: "image"; stamp: FileStamp; bytes: Base64; describedAs: string }
  | { kind: "other"; stamp: FileStamp; describedAs: string; size: number }
  | { kind: "unchanged"; stamp: FileStamp };

export interface FileStamp {
  size: number;
  modifiedAt: WireDate;
}

export interface FilesBrowseRequest {
  path?: string;
}

export interface FilesChangedNotification {
  agentID: UUID;
  folders: string[];
  many?: boolean;
}

export interface FilesListRequest {
  agentID: UUID;
  folder: string;
}

export interface FilesReadRequest {
  agentID: UUID;
  path: string;
  knownStamp?: FileStamp;
}

export interface FilesWatchRequest {
  agentID: UUID;
  folder: string;
}

export interface FolderHunk {
  oldStart: number;
  newStart: number;
  noNewlineAtEnd: boolean;
  lines: DiffLine[];
}

// uses: ChangesUnavailable
/** GitView (Model/AgentChanges.swift): `{ shared: { since } }`, `{ unavailable: … }` and so on. */
export type GitView =
  | { owned: { since: string } }
  | { shared: { since: string } }
  | { sharedFromHead: Record<string, never> }
  | { unavailable: ChangesUnavailable };

export interface Headline {
  h1: string;
  h2: string;
  h3: string;
}

export interface HelperLimits {
  running?: number;
  notArchived?: number;
  queued?: number;
  agentsMayArchive?: boolean;
}

export type HostID = string & { readonly __brand: "HostID" };

export interface HostJoinStatus {
  member: boolean;
  connected: boolean;
  problem?: string;
  at: WireDate;
}

export interface HostTunnel {
  up: boolean;
  problem?: string;
}

export interface LabelVocabularyRequest {
  folder: URLString;
}

export interface Lease {
  resource: ResourceName;
  displayName: string;
  holder: UUID;
  grantedAt: WireDate;
  expiresAt: WireDate;
  warned: boolean;
}

export interface LeaseSnapshot {
  resources: ResourceState[];
  at: WireDate;
}

export interface LineMember {
  agentID: UUID;
  askedAt: WireDate;
  isCallOpen: boolean;
}

export interface ListCursor {
  lastActivityAt: WireDate;
  id: UUID;
}

export interface ListRequest {
  includeArchived: boolean;
  archivedCommands: boolean;
  archivedOnly: boolean;
  folder?: URLString;
  startedByWorkflow?: string;
  limit?: number;
  lean: boolean;
  agentID?: UUID;
  after?: ListCursor;
  query?: string;
}

export interface MCPServer {
  name: string;
  transport: MCPServerTransport;
}

export type MCPServerTransport =
  | { stdio: { command: string; args: string[]; env: Record<string, string> } }
  | { http: { url: string; headers: Record<string, string> } }
  | { sse: { url: string; headers: Record<string, string> } };

export interface MCPTriggerFailure {
  code: MCPTriggerFailureCode;
  message: string;
  since: WireDate;
}

export type MCPTriggerFailureCode = "serverNotFound" | "badEventName" | "waitingForApproval" | "secretMissing" | "needsSignIn" | "unreachable" | "noEvents" | "eventNotOffered" | "noPollMode" | "badArguments" | "refused" | "serverError";

export interface MCPTriggerStatus {
  name: string;
  server?: string;
  state: MCPTriggerStatusState;
  lastPolledAt?: WireDate;
  lastEventAt?: WireDate;
  missedSince?: WireDate;
  failure?: MCPTriggerFailure;
  retryAt?: WireDate;
}

export type MCPTriggerStatusState = "pending" | "active" | "retrying" | "stopped" | "notThisHost";

export interface MarkRuntimeAvailable {
  credentialKey: string;
}

export interface MissingFolder {
  branchKept: boolean;
}

export type MoveAsker = "agent" | "person";

export type MoveTarget =
  | { newWorktree: { name?: string } }
  | { existing: { _0: URLString } }
  | { projectFolder: Record<string, never> };

export interface Need {
  id: NeedID;
  agentID: UUID;
  folder: URLString;
  kind: NeedKind;
  raisedAt: WireDate;
  headline: Headline;
}

/** NeedID (Attention/Need.swift): what is being answered, one key per kind. */
export type NeedID =
  | { permission: UUID }
  | { elicitation: UUID }
  | { report: { agentID: UUID; at: WireDate } };

export type NeedKind = "permission" | "elicitation" | "report";

export interface OptionsRequest {
  runtimeID: string;
  cwd: URLString;
  mcpServers: MCPServer[];
}

export interface OptionsResponse {
  draftID: UUID;
  options: ConfigOption[];
  commands: SlashCommand[];
}

export interface PagesChangedNotification {
  folder: URLString;
  folders: string[];
}

export type Parking =
  | { whenTurnEnds: { since: WireDate } }
  | { parked: { at: WireDate } };

export type Payment =
  | { allowance: { label?: string } }
  | { freeTier: { reset: ResetRule } }
  | { freeCredit: { amount?: Cost; expires?: WireDate } }
  | { prepaid: { amount?: Cost; expires?: WireDate } };

export interface PendingMove {
  target: MoveTarget;
  removeLeft: boolean;
  discardChanges: boolean;
  askedBy: MoveAsker;
  askedAt: WireDate;
}

export interface PermissionNotification {
  agentID: UUID;
  request?: PermissionRequest;
  requestID?: UUID;
}

export interface PermissionOption {
  optionID: string;
  name: string;
  kind: PermissionOptionKind;
}

export type PermissionOptionKind = "allow_once" | "allow_always" | "reject_once" | "reject_always" | "unknown";

export interface PermissionRequest {
  id: UUID;
  agentID: UUID;
  toolCall: ToolCall;
  options: PermissionOption[];
  askedAt: WireDate;
  subagent?: string;
}

export interface PinArrangeRequest {
  folder: URLString;
  paths: string[];
}

export interface PinArrangeSessionsRequest {
  folder: URLString;
  agentIDs: UUID[];
}

export type PinKind = "markdown" | "html" | "view";

export interface PinPathRequest {
  folder: URLString;
  path: string;
}

export interface PinReadRequest {
  folder: URLString;
  path: string;
  knownStamp?: FileStamp;
}

export interface PinRequest {
  folder: URLString;
  path: string;
  title?: string;
  view?: ViewPin;
}

export interface PinSessionRequest {
  folder: URLString;
  agentID: UUID;
}

export interface PinView {
  path: string;
  title: string;
  kind: PinKind;
  missing: boolean;
  pinnedBy: PinnerView;
  view?: ViewPin;
  missingReason?: string;
}

export interface PinWriteRequest {
  folder: URLString;
  path: string;
  text: string;
}

export type PinnerKind = "person" | "agent" | "workflow";

export interface PinnerView {
  kind: PinnerKind;
  id: string;
  name: string;
}

export interface PinsChangedNotification {
  folder: URLString;
  pins: PinView[];
  sessions?: UUID[];
}

export interface Plan {
  planID?: string;
  entries: PlanEntry[];
  state: PlanState;
  at: WireDate;
}

export interface PlanEntry {
  content: string;
  priority: PlanEntryPriority;
  status: PlanEntryStatus;
}

export type PlanEntryPriority = "high" | "medium" | "low";

export type PlanEntryStatus = "pending" | "in_progress" | "completed";

export type PlanState = "current" | "withdrawn";

export interface PresenceReport {
  watching?: UUID;
  active: boolean;
  mayNotify?: boolean;
  showing?: UUID;
}

export interface PrewarmRequest {
  agentID: UUID;
  why: PrewarmRequestWhy;
}

export type PrewarmRequestWhy = "opened" | "typing";

export interface Project {
  folder: URLString;
  archivedAt?: WireDate;
  addedAt: WireDate;
  laidOutAt?: WireDate;
  layoutVersion?: number;
  helperLimits?: HelperLimits;
  diskSpace?: DiskThresholds;
}

export interface ProjectDetection {
  enabled: boolean;
  paths: string[];
}

export interface ProjectPins {
  folder: URLString;
  pins: PinView[];
  sessions?: UUID[];
}

export interface ProjectRequest {
  folder: URLString;
}

export interface ProjectSummary {
  project: Project;
  name: string;
  exists: boolean;
  lastActivityAt: WireDate;
  counts: Partial<Record<AgentGroup, number>>;
  costToDate: Record<string, number>;
  unmeasuredAgents: number;
  retiredCount: number;
  isChat?: boolean;
}

export interface ProjectsListRequest {
  includeArchived: boolean;
}

export type PromptOrigin = "person" | "app";

export interface PromptRequest {
  agentID: UUID;
  text: string;
  attachments: Attachment[];
  from: PromptOrigin;
  sendID?: UUID;
}

export interface QueuedPrompt {
  id: UUID;
  text: string;
  attachments: Attachment[];
  queuedAt: WireDate;
  from: PromptOrigin;
  preface?: string;
}

export interface QueuedStart {
  runtimeID?: string;
  permissionMode?: string;
  model?: string;
  worktree?: WorktreeChoice;
  labels: string[];
}

export interface RateLimitInfo {
  status?: string;
  resetsAt?: WireDate;
  rateLimitType?: string;
  utilization?: number;
  overageStatus?: string;
  overageResetsAt?: WireDate;
  isUsingOverage?: boolean;
  overageInUse?: boolean;
  overageDisabledReason?: string;
}

export interface RememberedOptionsRequest {
  runtimeID: string;
  cwd: URLString;
}

export interface ReportedEdit {
  path: string;
  oldText?: string;
  newText: string;
  toolCallID: string;
  index: number;
  entryIndex: number;
  replaceAll: boolean;
  at: WireDate;
}

export type ResetRule =
  | { dailyAt: { hour: number; timeZone: string } }
  | { unknown: Record<string, never> };

export type ResourceKind = "screen" | "simulator" | "browser" | "named";

/** ResourceName (Model/Lease.swift): the name, trimmed and lower-cased, as a single string. */
export type ResourceName = string & { readonly __brand: "ResourceName" };

// uses: Lease, LineMember, DeclaredResource, ResourceKind, ResourceName
/**
 * ResourceState (Daemon/DaemonAPI.swift), as its encode(to:) writes it (#116): every holder in
 * `holds`, and the first again as `lease` for a reader from before counted holders. A host from
 * before #116 sends only `lease`, so `holds`, `places` and `declared` may be missing.
 */
export interface ResourceState {
  name: ResourceName;
  kind: ResourceKind;
  displayName: string;
  isGone: boolean;
  holds?: Lease[];
  lease?: Lease;
  places?: number;
  declared?: DeclaredResource;
  line: LineMember[];
  endingSoon: boolean;
}

export interface ResumingNotification {
  agentID: UUID;
  isResuming: boolean;
}

export interface ResumingResponse {
  agentIDs: UUID[];
}

export interface Runtime {
  id: string;
  name: string;
  executable: string;
  arguments: string[];
  install?: RuntimeInstall;
  installPage: URLString;
  usesAppCopyOnly: boolean;
}

export interface RuntimeAccount {
  runtimeID: string;
  state: RuntimeAccountState;
  authMethods: ACPAuthMethod[];
  canLogOut: boolean;
  providers: ACPProviderInfo[];
  currentProviderID?: string;
  signedInAs?: AuthStatus;
  promptCapabilities: ACPPromptCapabilities;
  canSteer: boolean;
  checkedAt: WireDate;
}

export type RuntimeAccountState = "ready" | "needsSignIn" | "unknown";

export interface RuntimeAllowances {
  rows: RuntimeAllowancesRow[];
  at: WireDate;
  shared?: AllowanceState[];
}

export interface RuntimeAllowancesRow {
  credentialKey: string;
  state: AllowanceState;
  unusable?: string;
}

export type RuntimeAvailability =
  | { available: { path: string; supportsResume: boolean } }
  | { missing: { lookedIn: string[] } }
  | { needsSignIn: { authMethods: string[]; fixCommand?: string } }
  | { failed: { reason: string } }
  | { installing: { progress?: string } }
  | { installFailed: { reason: string } };

export type RuntimeInstall =
  | { toolset: { runtimeID: string } }
  | { script: { url: URLString; shell: string } }
  | { npmGlobal: { package: string } };

export interface RuntimeStatus {
  runtime: Runtime;
  availability: RuntimeAvailability;
  checkedAt: WireDate;
  outdated: boolean;
  poolNote?: string;
  isOut?: boolean;
}

export type SandboxChoice = "runtime" | "on" | "off";

export interface SandboxFailureRecord {
  runtimeID: string;
  detail: string;
  hang: boolean;
  recoveryOffered: boolean;
  completedToolCalls: number;
}

export interface SandboxSettings {
  defaults: Record<string, SandboxChoice>;
}

export type SandboxState = "on" | "off" | "runtimeControlled" | "none";

export interface ServedRequest {
  kind: ServedRequestKind;
  outcome: ServedRequestOutcome;
}

export type ServedRequestKind =
  | { readFile: { path: string } }
  | { writeFile: { path: string; byteCount: number } }
  | { runCommand: { command: string; args: string[] } };

export type ServedRequestOutcome =
  | { served: Record<string, never> }
  | { refused: { reason: string } }
  | { failed: { message: string } };

export interface SessionLabel {
  value: string;
  owner: SessionLabelOwner;
  addedAt: WireDate;
}

export type SessionLabelOwner = "person" | "agent";

export interface SessionNotice {
  severity: string;
  title: string;
  detail?: string;
}

export interface SetCeilingRequest {
  agentID: UUID;
  ceiling?: Cost;
}

export interface SetLabelsRequest {
  agentID: UUID;
  add: string[];
  remove: string[];
}

export interface SetOptionRequest {
  agentID: UUID;
  optionID: string;
  value: JSONValue;
}

export interface SetSandboxRequest {
  agentID: UUID;
  choice?: SandboxChoice;
}

export interface SetUnreadRequest {
  agentID: UUID;
  unread: boolean;
}

export interface ShowFileNotification {
  agentID: UUID;
  file: ShownFile;
}

export interface ShownFile {
  path: string;
  line?: number;
}

export type SignInWantedReason = "notSignedIn" | "unreadable";

export interface SlashCommand {
  name: string;
  description?: string;
  inputHint?: string;
}

export interface StartOptions {
  values: Record<string, JSONValue>;
  extraArguments: string[];
}

export interface StartRequest {
  runtimeID: string;
  cwd: URLString;
  prompt: string;
  attachments: Attachment[];
  startOptions: StartOptions;
  draftID?: UUID;
  additionalDirectories: URLString[];
  mcpServers: MCPServer[];
  worktree?: WorktreeChoice;
  requestID?: UUID;
  sandbox?: SandboxChoice;
  labels: string[];
}

export interface StartingPoint {
  repository: URLString;
  commit: string;
}

export interface StopBackgroundRequest {
  agentID: UUID;
  itemID: string;
}

export interface StoreNotes {
  notes: string[];
}

export interface SuggestedPrompt {
  id: UUID;
  label: string;
  prompt: string;
}

/** Surface (Attention/Surface.swift): a tagged object, `{ mac: {} }` or `{ device: "<uuid>" }`. */
export type Surface = { mac: Record<string, never> } | { device: UUID };

export interface SurfaceIdentification {
  id: UUID;
  name: string;
  kind: DeviceKind;
}

export interface SwitchRecord {
  id: UUID;
  at: WireDate;
  agentID: UUID;
  from: SwitchRecordSide;
  to: SwitchRecordSide;
  reason: SwitchRecordReason;
  carried: CarriedSetting[];
  dropped: Dropped[];
  shortened?: number;
  billing: Payment;
  fromReturnsAt?: WireDate;
}

export type SwitchRecordReason = "allowanceSpent" | "overage" | "creditUsedUp" | "rateLimitPersisted" | "runtimeFailed" | "everyoneOutResumed" | "byHand";

export interface SwitchRecordSide {
  entryID?: UUID;
  runtimeID: string;
  model?: JSONValue;
  mode?: JSONValue;
}

export interface ToolCall {
  toolCallID?: string;
  title: string;
  name?: string;
  kind?: string;
  status?: string;
  content: ToolCallContent[];
  locations: ToolCallLocation[];
  rawInput?: JSONValue;
  rawOutput?: JSONValue;
  raw?: JSONValue;
}

// uses: ContentBlock
/**
 * ToolCallContent (ACP/ToolCallContent.swift): the protocol's shapes, as sent. Anything else is
 * written back as it came, so another `type` may arrive.
 */
export type ToolCallContent =
  | { type: "content"; content: ContentBlock }
  | { type: "diff"; path: string; newText: string; oldText?: string }
  | { type: "terminal"; terminalId: string };

export interface ToolCallLocation {
  path: string;
  line?: number;
}

export interface TranscriptEntry {
  id: UUID;
  at: WireDate;
  kind: TranscriptEntryKind;
  subagentID?: string;
}

export type TranscriptEntryKind =
  | { userMessage: { _0: string; blocks?: ContentBlock[]; from?: PromptOrigin } }
  | { agentMessage: { messageID?: string; text: string; blocks?: ContentBlock[] } }
  | { agentThought: { messageID?: string; text: string } }
  | { toolCall: { _0: ToolCall } }
  | { toolCallUpdate: { _0: ToolCall } }
  | { planUpdated: { _0: Plan } }
  | { usageRecorded: { _0: TurnUsage } }
  | { servedRequest: { _0: ServedRequest } }
  | { elicitationAsked: { _0: ElicitationRequest } }
  | { elicitationAnswered: { id: UUID; summary: string; answers?: ElicitationAnswer[] } }
  | { compaction: { status: string; summary: ContentBlock[]; id?: string; error?: string } }
  | { notice: { _0: SessionNotice } }
  | { permissionAsked: { _0: PermissionRequest } }
  | { permissionAnswered: { optionID: string; optionName?: string } }
  | { optionChanged: { id: string; value: JSONValue } }
  | { stateChanged: { _0: AgentState; reason?: EndedReason } }
  | { background: { _0: BackgroundItem } }
  | { workReported: { _0: WorkReport } }
  | { runtimeNote: { _0: string } }
  | { poolSwitch: { _0: SwitchRecord } }
  | { sandboxFailure: { _0: SandboxFailureRecord } }
  | { handoff: { markdown: string; characters: number } }
  | { settingsChanged: { _0: SwitchRecord } }
  | { appView: { _0: AppViewCall } };

export interface TranscriptPage {
  firstIndex: number;
  total: number;
  entries: TranscriptEntry[];
}

export interface TranscriptRequest {
  agentID: UUID;
  before?: number;
  limit: number;
  from?: number;
}

export interface TurnSummary {
  id: UUID;
  start: number;
  end: number;
  ask?: TranscriptEntry;
  last?: TranscriptEntry;
  concise?: TranscriptEntry[];
  outcome?: TranscriptEntry[];
  steps?: number;
  usage?: TurnUsage;
}

export interface TurnUsage {
  totalTokens: number;
  inputTokens: number;
  outputTokens: number;
  thoughtTokens?: number;
  cachedReadTokens?: number;
  cachedWriteTokens?: number;
  cost?: Cost;
}

export interface TurnsPage {
  turns: TurnSummary[];
  firstTurn: number;
  openStart: number;
}

export interface TurnsRequest {
  agentID: UUID;
  before?: number;
  limit: number;
}

export interface UnqueueRequest {
  agentID: UUID;
  promptID: UUID;
}

export interface Usage {
  used: number;
  size: number;
  cost?: Cost;
  at: WireDate;
}

export interface ViewCallRequest {
  agentID: UUID;
  project?: URLString;
  viewID: UUID;
  name: string;
  arguments?: JSONValue;
  feed?: boolean;
  server?: string;
}

export interface ViewContextRequest {
  agentID: UUID;
  viewID: UUID;
  uri?: string;
  content?: JSONValue;
  structuredContent?: JSONValue;
}

export interface ViewLogRequest {
  agentID: UUID;
  viewID: UUID;
  level?: string;
  data?: JSONValue;
}

export interface ViewPin {
  server: string;
  uri: string;
  tool: string;
  arguments?: JSONValue;
}

export interface ViewReadRequest {
  agentID: UUID;
  uri: string;
  server?: string;
  project?: URLString;
}

export interface ViewResource {
  uri: string;
  mimeType: string;
  html: string;
  policy: AppViewPolicy;
  prefersBorder?: boolean;
  variables: Record<string, string>;
}

export interface ViewShowRequest {
  agentID: UUID;
  project?: URLString;
  server: string;
  uri: string;
  hash: string;
  show: boolean;
}

export interface Wait {
  agentID: UUID;
  nameAtReport: string;
  ending?: WaitEnding;
}

export interface WaitEnding {
  at: WireDate;
  how: WaitEndingHow;
}

export type WaitEndingHow =
  | { finished: { outcome?: WorkOutcome; message?: string } }
  | { stopped: { _0?: EndedReason } }
  | { archived: Record<string, never> }
  | { gone: Record<string, never> };

export interface WaitStatus {
  line: string;
  mark: string;
  cancellable: boolean;
}

export interface WaitingAgent {
  agentID: UUID;
  title: string;
  folder: URLString;
  status: WaitStatus;
}

export interface WebRemoteStatus {
  port: number;
  served: boolean;
  reason?: string;
  detail?: string;
}

export type Weekday = "sun" | "mon" | "tue" | "wed" | "thu" | "fri" | "sat";

export type WorkOutcome = "done" | "nothing_to_do" | "needs_answer" | "partly_done" | "stuck" | "blocked";

export interface WorkReport {
  outcome: WorkOutcome;
  message: string;
  at: WireDate;
  block?: Block;
}

export interface Workflow {
  workflowID: string;
  folder: URLString;
  name: string;
  triggers: WorkflowTrigger[];
  mode: WorkflowMode;
  prompt: string;
  problem?: WorkflowProblem;
  unknownFields: Record<string, JSONValue>;
  settings: WorkflowSettings;
  cooldown?: number;
  enabled?: boolean;
  archived?: boolean;
  hosts?: string[];
  whenDone?: WorkflowWhenDone;
}

export interface WorkflowApproval {
  digest: string;
  isNew: boolean;
  note?: string;
}

export interface WorkflowApproveRequest {
  folder: URLString;
  workflowID: string;
  digest: string;
}

export interface WorkflowArchiveRequest {
  folder: URLString;
  workflowID: string;
  archived: boolean;
}

export type WorkflowCause =
  | { byHand: Record<string, never> }
  | { trigger: { _0: WorkflowTrigger } };

export interface WorkflowEnableRequest {
  folder: URLString;
  workflowID: string;
  enabled: boolean;
}

export type WorkflowLimit = "project" | "total";

export interface WorkflowMCPClearMissedRequest {
  folder: URLString;
  workflowID: string;
  name: string;
  server?: string;
}

export type WorkflowMode = "new" | "standing" | "triggering";

export type WorkflowOffReason = "file" | "writtenByAgent" | "agent" | "person";

export type WorkflowOutcome =
  | { ran: { agentID: UUID; at: WireDate } }
  | { refused: { _0: WorkflowRefusal; at: WireDate; repeats: number } };

export type WorkflowProblem =
  | { unreadable: { _0: string } }
  | { triggerNotSupported: { _0: string } }
  | { unsupportedMode: { _0: string } };

export type WorkflowRefusal =
  | { chainTooDeep: { depth: number } }
  | { runInFlight: Record<string, never> }
  | { queued: Record<string, never> }
  | { queueFull: { limit: number } }
  | { archived: Record<string, never> }
  | { disabled: Record<string, never> }
  | { overLimit: { _0: WorkflowLimit } }
  | { unreadable: { _0: string } }
  | { triggerNotSupported: { name: string } }
  | { agentUnavailable: Record<string, never> }
  | { noTriggeringAgent: Record<string, never> }
  | { missedWhileClosed: Record<string, never> }
  | { folderGone: Record<string, never> }
  | { dayLimitReached: Record<string, never> }
  | { settingRefused: { setting: string; detail: string } }
  | { awaitingApproval: Record<string, never> }
  | { deniedHere: Record<string, never> }
  | { coolingDown: { until?: WireDate } };

export interface WorkflowRemovedNotification {
  folder: URLString;
  workflowID: string;
}

export interface WorkflowRequest {
  folder: URLString;
  workflowID: string;
}

export interface WorkflowSchedule {
  minutes: number[];
  hours: [number, number];
  startMinute: number;
  endMinute: number;
  days: Weekday[];
}

export interface WorkflowSettings {
  permissionMode?: string;
  runtimeID?: string;
  model?: string;
  effort?: string;
  options: Record<string, string>;
  labels: string[];
}

export interface WorkflowSettingsRequest {
  folder: URLString;
  workflowID: string;
  settings: WorkflowSettings;
  cooldown?: string;
  labels?: string[];
  hosts?: string[];
  whenDone?: string;
}

export interface WorkflowSummary {
  workflow: Workflow;
  isArchived: boolean;
  isEnabled: boolean;
  overLimit?: WorkflowLimit;
  nextFireAt?: WireDate;
  nextFireAtByTrigger: (WireDate | null)[];
  lastOutcome?: WorkflowOutcome;
  causingEvent?: number;
  causingEventName?: string;
  isRunning: boolean;
  awaitingApproval?: WorkflowApproval;
  deniedHere?: WorkflowApproval;
  lastFiredAt?: WireDate;
  lastFiredBy?: WorkflowCause;
  cooldownEndsAt?: WireDate;
  holdsAFire: boolean;
  queued: number;
  offReason?: WorkflowOffReason;
  standingAgentID?: UUID;
  mcpTriggers?: MCPTriggerStatus[];
}

export type WorkflowTrigger = WorkflowTriggerStored;

export type WorkflowTriggerStored =
  | { schedule: { _0: WorkflowSchedule } }
  | { agentFinished: Record<string, never> }
  | { agentAskedPermission: Record<string, never> }
  | { agentAskedForm: Record<string, never> }
  | { agentStopped: Record<string, never> }
  | { workflowCompleted: { id?: string } }
  | { unrecognised: { name: string; keys: Record<string, JSONValue> } };

export type WorkflowWhenDone = "park" | "archive-allowed" | "archive";

export interface WorkflowsListRequest {
  folder?: URLString;
}

export type WorktreeChoice =
  | { new: Record<string, never> }
  | { existing: { _0: URLString } }
  | { named: { _0: string } }
  | { branch: { _0: string } };

export interface WorktreeStatus {
  uncommitted: number;
  ahead?: number;
  behind?: number;
  unmerged?: number;
}

export interface WorktreeSummary {
  name: string;
  root: URLString;
  branch?: string;
  isProjectFolder: boolean;
  exists: boolean;
  madeByApp: boolean;
  agents: UUID[];
  status?: WorktreeStatus;
}

export interface WorktreesListRequest {
  folder: URLString;
}

export interface WorktreesListResponse {
  isRepository: boolean;
  canMakeNew: boolean;
  whyNot?: string;
  worktrees: WorktreeSummary[];
  branches: BranchSummary[];
}

export interface WriteFailure {
  cause: WriteFailureCause;
  path?: string;
  what: string;
  message: string;
}

export type WriteFailureCause = "diskFull" | "notAllowed" | "readOnly";

/** Every method the web remote may call: its params and its result. */
export interface Methods {
  "agents/answerSandbox": { params: AnswerSandboxRequest; result: Agent };
  "agents/archive": { params: AgentRequest; result: Empty };
  "agents/continueInProject": { params: ContinueInProjectRequest; result: UUID };
  "agents/delete": { params: AgentRequest; result: Empty };
  "agents/discardDraft": { params: DiscardDraftRequest; result: Empty };
  "agents/fork": { params: AgentRequest; result: UUID };
  "agents/labelVocabulary": { params: LabelVocabularyRequest; result: string[] };
  "agents/list": { params: ListRequest; result: Agent[] };
  "agents/options": { params: OptionsRequest; result: OptionsResponse };
  "agents/park": { params: AgentRequest; result: Empty };
  "agents/prewarm": { params: PrewarmRequest; result: Empty };
  "agents/prompt": { params: PromptRequest; result: Empty };
  "agents/recreateWorktree": { params: AgentRequest; result: Agent };
  "agents/resuming": { params: Empty; result: ResumingResponse };
  "agents/sendNow": { params: UnqueueRequest; result: Empty };
  "agents/setCeiling": { params: SetCeilingRequest; result: Agent };
  "agents/setLabels": { params: SetLabelsRequest; result: Agent };
  "agents/setOption": { params: SetOptionRequest; result: ConfigOption[] };
  "agents/setSandbox": { params: SetSandboxRequest; result: Agent };
  "agents/setUnread": { params: SetUnreadRequest; result: Empty };
  "agents/start": { params: StartRequest; result: UUID };
  "agents/stop": { params: AgentRequest; result: Empty };
  "agents/stopBackground": { params: StopBackgroundRequest; result: JSONValue };
  "agents/touchedPaths": { params: AgentRequest; result: string[] };
  "agents/transcript": { params: TranscriptRequest; result: TranscriptPage };
  "agents/turns": { params: TurnsRequest; result: TurnsPage };
  "agents/unarchive": { params: AgentRequest; result: Empty };
  "agents/unpark": { params: AgentRequest; result: Empty };
  "agents/unqueue": { params: UnqueueRequest; result: Empty };
  "artifact/write": { params: ArtifactWriteRequest; result: Empty };
  "attention/pending": { params: Empty; result: AttentionPending };
  "changes/file": { params: ChangesFileRequest; result: ChangedFileDetail };
  "changes/list": { params: ChangesListRequest; result: ChangesList };
  "clients/forgetSelf": { params: Empty; result: Empty };
  "control/status": { params: Empty; result: ControlStatus };
  "cost/state": { params: Empty; result: CostState };
  "credentials/lend": { params: CredentialsLend; result: Empty };
  "credentials/offer": { params: CredentialsOffer; result: Empty };
  "disk/state": { params: Empty; result: DiskState };
  "dropbox/put": { params: DropboxPutRequest; result: DropboxPutResponse };
  "elicitations/answer": { params: AnswerElicitationRequest; result: Empty };
  "elicitations/pending": { params: Empty; result: ElicitationRequest[] };
  "events/list": { params: EventsListRequest; result: EventsPage };
  "files/browse": { params: FilesBrowseRequest; result: DirectoryListing };
  "files/list": { params: FilesListRequest; result: DirectoryListing };
  "files/mention": { params: FileMentionRequest; result: FileMentionDTO[] };
  "files/read": { params: FilesReadRequest; result: FileReading };
  "files/unwatch": { params: FilesWatchRequest; result: Empty };
  "files/watch": { params: FilesWatchRequest; result: Empty };
  "hosts/list": { params: Empty; result: ControlHost[] };
  "leases/snapshot": { params: Empty; result: LeaseSnapshot };
  "modes/remembered": { params: Empty; result: Record<string, JSONValue> };
  "options/remembered": { params: RememberedOptionsRequest; result: ConfigOption[] };
  "permissions/answer": { params: AnswerRequest; result: Empty };
  "permissions/pending": { params: Empty; result: PermissionRequest[] };
  "pins/arrange": { params: PinArrangeRequest; result: Empty };
  "pins/arrangeSessions": { params: PinArrangeSessionsRequest; result: Empty };
  "pins/list": { params: Empty; result: ProjectPins[] };
  "pins/pin": { params: PinRequest; result: PinView[] };
  "pins/pinSession": { params: PinSessionRequest; result: Empty };
  "pins/read": { params: PinReadRequest; result: FileReading };
  "pins/unpin": { params: PinPathRequest; result: Empty };
  "pins/unpinSession": { params: PinSessionRequest; result: Empty };
  "pins/write": { params: PinWriteRequest; result: Empty };
  "presence/report": { params: PresenceReport; result: Empty };
  "projects/add": { params: ProjectRequest; result: ProjectSummary };
  "projects/chatState": { params: Empty; result: ChatProjectState };
  "projects/clone": { params: CloneRequest; result: ProjectSummary };
  "projects/clones": { params: Empty; result: CloneSummary[] };
  "projects/list": { params: ProjectsListRequest; result: ProjectSummary[] };
  "projects/unarchive": { params: ProjectRequest; result: ProjectSummary };
  "runtimes/accounts": { params: Empty; result: RuntimeAccount[] };
  "runtimes/allowances": { params: string | null; result: RuntimeAllowances };
  "runtimes/list": { params: Empty; result: RuntimeStatus[] };
  "runtimes/markAvailable": { params: MarkRuntimeAvailable; result: RuntimeAllowances };
  "sandbox/state": { params: Empty; result: SandboxSettings };
  "store/notes": { params: Empty; result: StoreNotes };
  "surface/identify": { params: SurfaceIdentification; result: Empty };
  "views/call": { params: ViewCallRequest; result: JSONValue };
  "views/context": { params: ViewContextRequest; result: Empty };
  "views/log": { params: ViewLogRequest; result: Empty };
  "views/read": { params: ViewReadRequest; result: ViewResource };
  "views/show": { params: ViewShowRequest; result: Empty };
  "workflows/approve": { params: WorkflowApproveRequest; result: WorkflowSummary };
  "workflows/archive": { params: WorkflowArchiveRequest; result: WorkflowSummary };
  "workflows/deny": { params: WorkflowApproveRequest; result: WorkflowSummary };
  "workflows/enable": { params: WorkflowEnableRequest; result: WorkflowSummary };
  "workflows/list": { params: WorkflowsListRequest; result: WorkflowSummary[] };
  "workflows/mcpTrigger/clearMissed": { params: WorkflowMCPClearMissedRequest; result: WorkflowSummary };
  "workflows/run": { params: WorkflowRequest; result: WorkflowSummary };
  "workflows/settings": { params: WorkflowSettingsRequest; result: WorkflowSummary };
  "worktrees/list": { params: WorktreesListRequest; result: WorktreesListResponse };
}

/** Whether a method goes to a host (with `h`) or to the control plane itself. */
export const MethodTarget = {
  "agents/answerSandbox": "host",
  "agents/archive": "host",
  "agents/continueInProject": "host",
  "agents/delete": "host",
  "agents/discardDraft": "host",
  "agents/fork": "host",
  "agents/labelVocabulary": "host",
  "agents/list": "host",
  "agents/options": "host",
  "agents/park": "host",
  "agents/prewarm": "host",
  "agents/prompt": "host",
  "agents/recreateWorktree": "host",
  "agents/resuming": "host",
  "agents/sendNow": "host",
  "agents/setCeiling": "host",
  "agents/setLabels": "host",
  "agents/setOption": "host",
  "agents/setSandbox": "host",
  "agents/setUnread": "host",
  "agents/start": "host",
  "agents/stop": "host",
  "agents/stopBackground": "host",
  "agents/touchedPaths": "host",
  "agents/transcript": "host",
  "agents/turns": "host",
  "agents/unarchive": "host",
  "agents/unpark": "host",
  "agents/unqueue": "host",
  "artifact/write": "host",
  "attention/pending": "host",
  "changes/file": "host",
  "changes/list": "host",
  "clients/forgetSelf": "control",
  "control/status": "control",
  "cost/state": "host",
  "credentials/lend": "host",
  "credentials/offer": "host",
  "disk/state": "host",
  "dropbox/put": "host",
  "elicitations/answer": "host",
  "elicitations/pending": "host",
  "events/list": "host",
  "files/browse": "host",
  "files/list": "host",
  "files/mention": "host",
  "files/read": "host",
  "files/unwatch": "host",
  "files/watch": "host",
  "hosts/list": "control",
  "leases/snapshot": "host",
  "modes/remembered": "host",
  "options/remembered": "host",
  "permissions/answer": "host",
  "permissions/pending": "host",
  "pins/arrange": "host",
  "pins/arrangeSessions": "host",
  "pins/list": "host",
  "pins/pin": "host",
  "pins/pinSession": "host",
  "pins/read": "host",
  "pins/unpin": "host",
  "pins/unpinSession": "host",
  "pins/write": "host",
  "presence/report": "host",
  "projects/add": "host",
  "projects/chatState": "host",
  "projects/clone": "host",
  "projects/clones": "host",
  "projects/list": "host",
  "projects/unarchive": "host",
  "runtimes/accounts": "host",
  "runtimes/allowances": "host",
  "runtimes/list": "host",
  "runtimes/markAvailable": "host",
  "sandbox/state": "host",
  "store/notes": "host",
  "surface/identify": "host",
  "views/call": "host",
  "views/context": "host",
  "views/log": "host",
  "views/read": "host",
  "views/show": "host",
  "workflows/approve": "host",
  "workflows/archive": "host",
  "workflows/deny": "host",
  "workflows/enable": "host",
  "workflows/list": "host",
  "workflows/mcpTrigger/clearMissed": "host",
  "workflows/run": "host",
  "workflows/settings": "host",
  "worktrees/list": "host",
} as const;

/** Every notification the web remote hears, and its params. */
export interface Notifications {
  "agent/changed": Agent;
  "agent/elicitation": ElicitationNotification;
  "agent/entry": EntryNotification;
  "agent/permission": PermissionNotification;
  "agent/removed": AgentRemovedNotification;
  "agent/resuming": ResumingNotification;
  "agent/showFile": ShowFileNotification;
  "agents/draftOptions": DraftOptionsNotification;
  "attention/changed": AttentionNotification;
  "clone/changed": CloneNotification;
  "control/hostChanged": JSONValue;
  "disk/changed": DiskState;
  "files/changed": FilesChangedNotification;
  "leases/changed": LeaseSnapshot;
  "modes/changed": Record<string, JSONValue>;
  "pages/changed": PagesChangedNotification;
  "pins/changed": PinsChangedNotification;
  "project/changed": ProjectSummary;
  "storage/writeFailed": WriteFailure;
  "store/notesChanged": StoreNotes;
  "workflow/changed": WorkflowSummary;
  "workflow/removed": WorkflowRemovedNotification;
}

/** Each interface's keys, for checking Swift-encoded fixtures against these types. */
export const Shapes: Record<string, { required: readonly string[]; optional: readonly string[] }> = {
  ACPAuthMethod: { required: ["id"], optional: ["name", "description", "_meta"] },
  ACPPromptCapabilities: { required: [], optional: ["image", "audio", "embeddedContext"] },
  ACPProviderInfo: { required: ["id"], optional: ["name", "protocol", "configured"] },
  Agent: { required: ["id", "runtimeID", "cwd", "state", "startOptions", "advertisedOptions", "availableCommands", "createdAt", "lastActivityAt"], optional: ["title", "labels", "runtimeSessionID", "isUnread", "reportSeenAt", "endedReason", "archivedReason", "usage", "lastTurnUsage", "costToDate", "costCeiling", "plans", "background", "additionalDirectories", "mcpServers", "queuedPrompts", "suggestedPrompts", "startedByWorkflow", "startedByRun", "startedByAgent", "chainDepth", "eventWait", "worktree", "pendingMove", "startingPoint", "startRequestID", "restartPickUps", "report", "outcomeAsked", "titledByAgent", "parking", "afterTurn", "archivedAt", "sandboxOverride", "effectiveSandbox", "pendingSandboxFailure", "missingFolder", "listsLeftOut", "madeInRoot", "queuedStart"] },
  AgentRemovedNotification: { required: ["agentID"], optional: [] },
  AgentRequest: { required: ["agentID"], optional: [] },
  AgentWorktree: { required: ["name", "root", "project", "madeByApp"], optional: ["branch", "base"] },
  AllowanceReading: { required: ["spent", "nearlySpent", "at"], optional: ["window", "used", "resetsAt"] },
  AllowanceState: { required: ["credentialKey", "entryID", "status", "since", "changedAt", "learnedFrom", "spent", "rateLimitStreak"], optional: ["lastRateLimit", "reading", "modelsOut"] },
  AllowanceStateModelOut: { required: ["model", "since", "retryAfter"], optional: ["name"] },
  AnswerElicitationRequest: { required: ["requestID", "action", "content"], optional: ["sendID"] },
  AnswerRequest: { required: ["permissionID", "optionID"], optional: ["sendID"] },
  AnswerSandboxRequest: { required: ["agentID", "carryOn"], optional: [] },
  AppViewCall: { required: ["id", "server", "tool", "resourceUri", "state"], optional: ["arguments", "result", "reason", "pinnable"] },
  AppViewPolicy: { required: ["connectDomains", "resourceDomains", "frameDomains", "baseUriDomains", "refused"], optional: [] },
  ArtifactWriteRequest: { required: ["agentID", "path", "text"], optional: [] },
  Attachment: { required: ["id", "block", "displayName"], optional: ["byteCount"] },
  AttentionDelivery: { required: ["needID"], optional: ["to"] },
  AttentionNotification: { required: ["needID", "alert"], optional: ["need", "to"] },
  AttentionPending: { required: ["needs", "deliveries"], optional: [] },
  AuthStatus: { required: ["kind", "label"], optional: [] },
  BackgroundItem: { required: ["id", "kind", "name", "state", "canStop", "isStopping", "startedAt"], optional: ["taskType", "detail", "command", "parentID", "toolCallID", "outputFilePath", "summary", "lastToolName", "endedAt"] },
  Block: { required: ["waits"], optional: ["checkAgainAt", "wakeOn", "clearedAt", "clearedBy"] },
  BranchSummary: { required: ["name"], optional: ["remote"] },
  CarriedSetting: { required: ["optionID", "name", "source"], optional: ["from", "to"] },
  ChangedFile: { required: ["path", "source", "state", "editCount", "beyondReported", "inProgress", "outsideFolder"], optional: ["relativePath", "added", "removed", "firstLine", "oldPath"] },
  ChangedFileDetail: { required: ["file", "edits"], optional: ["hunks", "whole"] },
  ChangesFileRequest: { required: ["agentID", "path", "whole"], optional: [] },
  ChangesList: { required: ["files", "git", "reportsEdits"], optional: ["more"] },
  ChangesListRequest: { required: ["agentID"], optional: [] },
  CloneNotification: { required: ["clone", "finished"], optional: [] },
  CloneRequest: { required: ["url"], optional: [] },
  CloneSummary: { required: ["id", "url", "folder", "startedAt"], optional: [] },
  ConfigChoice: { required: ["value", "name"], optional: ["description"] },
  ConfigChoiceGroup: { required: ["options"], optional: ["name", "group"] },
  ContentBlockAnnotations: { required: [], optional: ["audience", "priority"] },
  ContinueInProjectRequest: { required: ["agentID", "text", "attachments"], optional: ["requestID"] },
  ControlHost: { required: ["id", "name", "platform", "version", "state", "reach"], optional: ["machineID", "relay", "signInFrom", "tunnel"] },
  ControlStatus: { required: ["name", "version", "machineID"], optional: ["homeHost", "startedAt", "port", "awayFromHome", "you", "relayKey", "web", "thisMacHost", "projectDetection"] },
  Cost: { required: ["amount", "currency"], optional: [] },
  CostLimits: { required: [], optional: ["perAgent", "daily"] },
  CostState: { required: ["limits", "today", "day"], optional: ["note"] },
  CredentialsLend: { required: ["runtime", "kind", "secret"], optional: [] },
  CredentialsOffer: { required: ["runtimes", "ownSignInOnly"], optional: ["notRelayed", "signIns"] },
  DeclaredResource: { required: ["name", "displayName", "description", "holders"], optional: ["defaultMinutes", "maximumMinutes"] },
  DiffLine: { required: ["kind", "text"], optional: ["newLine"] },
  DirectoryEntry: { required: ["url", "name", "isDirectory"], optional: ["size", "modifiedAt"] },
  DirectoryListing: { required: ["url", "entries", "omitted"], optional: [] },
  DiscardDraftRequest: { required: ["draftID"], optional: [] },
  DiskAlarm: { required: ["reading", "level", "threshold", "worktrees"], optional: [] },
  DiskReading: { required: ["volume", "mount", "freeBytes", "totalBytes"], optional: [] },
  DiskState: { required: ["alarms"], optional: [] },
  DiskThresholds: { required: [], optional: ["lowGB", "lowPercent", "criticalGB"] },
  DiskWorktree: { required: ["name", "bytes", "partial"], optional: [] },
  DraftOptionsNotification: { required: ["draftID", "options", "commands"], optional: ["failure"] },
  DropboxPutRequest: { required: ["folder", "name", "data"], optional: ["subfolder"] },
  DropboxPutResponse: { required: ["path"], optional: [] },
  EffectiveSandbox: { required: ["state", "requested"], optional: ["reason"] },
  ElicitationAnswer: { required: ["question", "answer"], optional: [] },
  ElicitationNotification: { required: ["agentID", "requestID"], optional: ["request"] },
  ElicitationRequest: { required: ["id", "agentID", "mode", "scope", "askedAt"], optional: ["elicitationID", "message"] },
  ElicitationSchema: { required: ["properties"], optional: ["title", "description"] },
  ElicitationSchemaProperty: { required: ["name", "isRequired", "kind"], optional: ["title", "description", "defaultValue"] },
  ElicitationSchemaPropertyChoice: { required: ["value", "title"], optional: ["description"] },
  Empty: { required: [], optional: [] },
  EntryNotification: { required: ["agentID", "entry"], optional: ["index", "oversized"] },
  Event: { required: ["position", "name", "at", "count", "scope", "sentence", "details", "chainDepth", "consequences"], optional: ["lastAt", "publisher", "message"] },
  EventPublisher: { required: ["agentID", "title"], optional: [] },
  EventWait: { required: ["id", "patterns", "from", "since"], optional: ["deadline", "ending", "resumePromptID"] },
  EventsListRequest: { required: ["limit"], optional: ["before", "scope", "groups"] },
  EventsPage: { required: ["events", "waiting", "hasMore"], optional: [] },
  FileMentionDTO: { required: ["path", "relativePath"], optional: [] },
  FileMentionRequest: { required: ["agentID", "term"], optional: [] },
  FileStamp: { required: ["size", "modifiedAt"], optional: [] },
  FilesBrowseRequest: { required: [], optional: ["path"] },
  FilesChangedNotification: { required: ["agentID", "folders"], optional: ["many"] },
  FilesListRequest: { required: ["agentID", "folder"], optional: [] },
  FilesReadRequest: { required: ["agentID", "path"], optional: ["knownStamp"] },
  FilesWatchRequest: { required: ["agentID", "folder"], optional: [] },
  FolderHunk: { required: ["oldStart", "newStart", "noNewlineAtEnd", "lines"], optional: [] },
  Headline: { required: ["h1", "h2", "h3"], optional: [] },
  HelperLimits: { required: [], optional: ["running", "notArchived", "queued", "agentsMayArchive"] },
  HostJoinStatus: { required: ["member", "connected", "at"], optional: ["problem"] },
  HostTunnel: { required: ["up"], optional: ["problem"] },
  LabelVocabularyRequest: { required: ["folder"], optional: [] },
  Lease: { required: ["resource", "displayName", "holder", "grantedAt", "expiresAt", "warned"], optional: [] },
  LeaseSnapshot: { required: ["resources", "at"], optional: [] },
  LineMember: { required: ["agentID", "askedAt", "isCallOpen"], optional: [] },
  ListCursor: { required: ["lastActivityAt", "id"], optional: [] },
  ListRequest: { required: ["includeArchived", "archivedCommands", "archivedOnly", "lean"], optional: ["folder", "startedByWorkflow", "limit", "agentID", "after", "query"] },
  MCPServer: { required: ["name", "transport"], optional: [] },
  MCPTriggerFailure: { required: ["code", "message", "since"], optional: [] },
  MCPTriggerStatus: { required: ["name", "state"], optional: ["server", "lastPolledAt", "lastEventAt", "missedSince", "failure", "retryAt"] },
  MarkRuntimeAvailable: { required: ["credentialKey"], optional: [] },
  MissingFolder: { required: ["branchKept"], optional: [] },
  Need: { required: ["id", "agentID", "folder", "kind", "raisedAt", "headline"], optional: [] },
  OptionsRequest: { required: ["runtimeID", "cwd", "mcpServers"], optional: [] },
  OptionsResponse: { required: ["draftID", "options", "commands"], optional: [] },
  PagesChangedNotification: { required: ["folder", "folders"], optional: [] },
  PendingMove: { required: ["target", "removeLeft", "discardChanges", "askedBy", "askedAt"], optional: [] },
  PermissionNotification: { required: ["agentID"], optional: ["request", "requestID"] },
  PermissionOption: { required: ["optionID", "name", "kind"], optional: [] },
  PermissionRequest: { required: ["id", "agentID", "toolCall", "options", "askedAt"], optional: ["subagent"] },
  PinArrangeRequest: { required: ["folder", "paths"], optional: [] },
  PinArrangeSessionsRequest: { required: ["folder", "agentIDs"], optional: [] },
  PinPathRequest: { required: ["folder", "path"], optional: [] },
  PinReadRequest: { required: ["folder", "path"], optional: ["knownStamp"] },
  PinRequest: { required: ["folder", "path"], optional: ["title", "view"] },
  PinSessionRequest: { required: ["folder", "agentID"], optional: [] },
  PinView: { required: ["path", "title", "kind", "missing", "pinnedBy"], optional: ["view", "missingReason"] },
  PinWriteRequest: { required: ["folder", "path", "text"], optional: [] },
  PinnerView: { required: ["kind", "id", "name"], optional: [] },
  PinsChangedNotification: { required: ["folder", "pins"], optional: ["sessions"] },
  Plan: { required: ["entries", "state", "at"], optional: ["planID"] },
  PlanEntry: { required: ["content", "priority", "status"], optional: [] },
  PresenceReport: { required: ["active"], optional: ["watching", "mayNotify", "showing"] },
  PrewarmRequest: { required: ["agentID", "why"], optional: [] },
  Project: { required: ["folder", "addedAt"], optional: ["archivedAt", "laidOutAt", "layoutVersion", "helperLimits", "diskSpace"] },
  ProjectDetection: { required: ["enabled", "paths"], optional: [] },
  ProjectPins: { required: ["folder", "pins"], optional: ["sessions"] },
  ProjectRequest: { required: ["folder"], optional: [] },
  ProjectSummary: { required: ["project", "name", "exists", "lastActivityAt", "counts", "costToDate", "unmeasuredAgents", "retiredCount"], optional: ["isChat"] },
  ProjectsListRequest: { required: ["includeArchived"], optional: [] },
  PromptRequest: { required: ["agentID", "text", "attachments", "from"], optional: ["sendID"] },
  QueuedPrompt: { required: ["id", "text", "attachments", "queuedAt", "from"], optional: ["preface"] },
  QueuedStart: { required: ["labels"], optional: ["runtimeID", "permissionMode", "model", "worktree"] },
  RateLimitInfo: { required: [], optional: ["status", "resetsAt", "rateLimitType", "utilization", "overageStatus", "overageResetsAt", "isUsingOverage", "overageInUse", "overageDisabledReason"] },
  RememberedOptionsRequest: { required: ["runtimeID", "cwd"], optional: [] },
  ReportedEdit: { required: ["path", "newText", "toolCallID", "index", "entryIndex", "replaceAll", "at"], optional: ["oldText"] },
  ResumingNotification: { required: ["agentID", "isResuming"], optional: [] },
  ResumingResponse: { required: ["agentIDs"], optional: [] },
  Runtime: { required: ["id", "name", "executable", "arguments", "installPage", "usesAppCopyOnly"], optional: ["install"] },
  RuntimeAccount: { required: ["runtimeID", "state", "authMethods", "canLogOut", "providers", "promptCapabilities", "canSteer", "checkedAt"], optional: ["currentProviderID", "signedInAs"] },
  RuntimeAllowances: { required: ["rows", "at"], optional: ["shared"] },
  RuntimeAllowancesRow: { required: ["credentialKey", "state"], optional: ["unusable"] },
  RuntimeStatus: { required: ["runtime", "availability", "checkedAt", "outdated"], optional: ["poolNote", "isOut"] },
  SandboxFailureRecord: { required: ["runtimeID", "detail", "hang", "recoveryOffered", "completedToolCalls"], optional: [] },
  SandboxSettings: { required: ["defaults"], optional: [] },
  ServedRequest: { required: ["kind", "outcome"], optional: [] },
  SessionLabel: { required: ["value", "owner", "addedAt"], optional: [] },
  SessionNotice: { required: ["severity", "title"], optional: ["detail"] },
  SetCeilingRequest: { required: ["agentID"], optional: ["ceiling"] },
  SetLabelsRequest: { required: ["agentID", "add", "remove"], optional: [] },
  SetOptionRequest: { required: ["agentID", "optionID", "value"], optional: [] },
  SetSandboxRequest: { required: ["agentID"], optional: ["choice"] },
  SetUnreadRequest: { required: ["agentID", "unread"], optional: [] },
  ShowFileNotification: { required: ["agentID", "file"], optional: [] },
  ShownFile: { required: ["path"], optional: ["line"] },
  SlashCommand: { required: ["name"], optional: ["description", "inputHint"] },
  StartOptions: { required: ["values", "extraArguments"], optional: [] },
  StartRequest: { required: ["runtimeID", "cwd", "prompt", "attachments", "startOptions", "additionalDirectories", "mcpServers", "labels"], optional: ["draftID", "worktree", "requestID", "sandbox"] },
  StartingPoint: { required: ["repository", "commit"], optional: [] },
  StopBackgroundRequest: { required: ["agentID", "itemID"], optional: [] },
  StoreNotes: { required: ["notes"], optional: [] },
  SuggestedPrompt: { required: ["id", "label", "prompt"], optional: [] },
  SurfaceIdentification: { required: ["id", "name", "kind"], optional: [] },
  SwitchRecord: { required: ["id", "at", "agentID", "from", "to", "reason", "carried", "dropped", "billing"], optional: ["shortened", "fromReturnsAt"] },
  SwitchRecordSide: { required: ["runtimeID"], optional: ["entryID", "model", "mode"] },
  ToolCall: { required: ["title", "content", "locations"], optional: ["toolCallID", "name", "kind", "status", "rawInput", "rawOutput", "raw"] },
  ToolCallLocation: { required: ["path"], optional: ["line"] },
  TranscriptEntry: { required: ["id", "at", "kind"], optional: ["subagentID"] },
  TranscriptPage: { required: ["firstIndex", "total", "entries"], optional: [] },
  TranscriptRequest: { required: ["agentID", "limit"], optional: ["before", "from"] },
  TurnSummary: { required: ["id", "start", "end"], optional: ["ask", "last", "concise", "outcome", "steps", "usage"] },
  TurnUsage: { required: ["totalTokens", "inputTokens", "outputTokens"], optional: ["thoughtTokens", "cachedReadTokens", "cachedWriteTokens", "cost"] },
  TurnsPage: { required: ["turns", "firstTurn", "openStart"], optional: [] },
  TurnsRequest: { required: ["agentID", "limit"], optional: ["before"] },
  UnqueueRequest: { required: ["agentID", "promptID"], optional: [] },
  Usage: { required: ["used", "size", "at"], optional: ["cost"] },
  ViewCallRequest: { required: ["agentID", "viewID", "name"], optional: ["project", "arguments", "feed", "server"] },
  ViewContextRequest: { required: ["agentID", "viewID"], optional: ["uri", "content", "structuredContent"] },
  ViewLogRequest: { required: ["agentID", "viewID"], optional: ["level", "data"] },
  ViewPin: { required: ["server", "uri", "tool"], optional: ["arguments"] },
  ViewReadRequest: { required: ["agentID", "uri"], optional: ["server", "project"] },
  ViewResource: { required: ["uri", "mimeType", "html", "policy", "variables"], optional: ["prefersBorder"] },
  ViewShowRequest: { required: ["agentID", "server", "uri", "hash", "show"], optional: ["project"] },
  Wait: { required: ["agentID", "nameAtReport"], optional: ["ending"] },
  WaitEnding: { required: ["at", "how"], optional: [] },
  WaitStatus: { required: ["line", "mark", "cancellable"], optional: [] },
  WaitingAgent: { required: ["agentID", "title", "folder", "status"], optional: [] },
  WebRemoteStatus: { required: ["port", "served"], optional: ["reason", "detail"] },
  WorkReport: { required: ["outcome", "message", "at"], optional: ["block"] },
  Workflow: { required: ["workflowID", "folder", "name", "triggers", "mode", "prompt", "unknownFields", "settings"], optional: ["problem", "cooldown", "enabled", "archived", "hosts", "whenDone"] },
  WorkflowApproval: { required: ["digest", "isNew"], optional: ["note"] },
  WorkflowApproveRequest: { required: ["folder", "workflowID", "digest"], optional: [] },
  WorkflowArchiveRequest: { required: ["folder", "workflowID", "archived"], optional: [] },
  WorkflowEnableRequest: { required: ["folder", "workflowID", "enabled"], optional: [] },
  WorkflowMCPClearMissedRequest: { required: ["folder", "workflowID", "name"], optional: ["server"] },
  WorkflowRemovedNotification: { required: ["folder", "workflowID"], optional: [] },
  WorkflowRequest: { required: ["folder", "workflowID"], optional: [] },
  WorkflowSchedule: { required: ["minutes", "hours", "startMinute", "endMinute", "days"], optional: [] },
  WorkflowSettings: { required: ["options", "labels"], optional: ["permissionMode", "runtimeID", "model", "effort"] },
  WorkflowSettingsRequest: { required: ["folder", "workflowID", "settings"], optional: ["cooldown", "labels", "hosts", "whenDone"] },
  WorkflowSummary: { required: ["workflow", "isArchived", "isEnabled", "nextFireAtByTrigger", "isRunning", "holdsAFire", "queued"], optional: ["overLimit", "nextFireAt", "lastOutcome", "causingEvent", "causingEventName", "awaitingApproval", "deniedHere", "lastFiredAt", "lastFiredBy", "cooldownEndsAt", "offReason", "standingAgentID", "mcpTriggers"] },
  WorkflowsListRequest: { required: [], optional: ["folder"] },
  WorktreeStatus: { required: ["uncommitted"], optional: ["ahead", "behind", "unmerged"] },
  WorktreeSummary: { required: ["name", "root", "isProjectFolder", "exists", "madeByApp", "agents"], optional: ["branch", "status"] },
  WorktreesListRequest: { required: ["folder"], optional: [] },
  WorktreesListResponse: { required: ["isRepository", "canMakeNew", "worktrees", "branches"], optional: ["whyNot"] },
  WriteFailure: { required: ["cause", "what", "message"], optional: ["path"] },
};
