import Foundation
import SwiftParser
import SwiftSyntax

/// Makes Web/src/protocol/generated.ts from AgentsKitCore's source (071, research R6,
/// contracts/generated-types.md).
///
/// The same source always gives the same bytes: types sorted by name, and no date or commit
/// in the header. T019 fills in the emitter; until then it writes the header only, having
/// parsed every input file, so a missing or unparseable input already fails.
public struct Generator: Sendable {
    /// Where the output goes, from the repository root.
    public static let output = "Web/src/protocol/generated.ts"

    /// What is read, from the repository root. Adding a file is a reviewed code change.
    public static let inputs: [Input] = [
        .glob(folder: "Packages/AgentsKit/Sources/AgentsKitCore/Daemon", prefix: "DaemonAPI"),
        .file("Packages/AgentsKit/Sources/AgentsKitCore/Control/DaemonAPI+Control.swift"),
        .file("Packages/AgentsKit/Sources/AgentsKitCore/Control/Grant.swift"),
        .file("Packages/AgentsKit/Sources/AgentsKitCore/Control/ControlAuth.swift"),
        .tree("Packages/AgentsKit/Sources/AgentsKitCore/Model"),
    ]

    public enum Input: Sendable, Equatable {
        case file(String)
        /// The `.swift` files directly in `folder` whose names start with `prefix`.
        case glob(folder: String, prefix: String)
        /// Every `.swift` file under `folder`.
        case tree(String)
    }

    public struct Failure: Error, CustomStringConvertible, Equatable {
        public var description: String
        public init(_ description: String) { self.description = description }
    }

    public let root: URL

    public init(root: URL) { self.root = root }

    /// The repository paths of every input file, sorted.
    public func inputFiles() throws -> [String] {
        let manager = FileManager.default
        var paths: [String] = []
        for input in Self.inputs {
            switch input {
            case .file(let path):
                guard manager.fileExists(atPath: root.appending(path: path).path) else {
                    throw Failure("\(path) is an input but does not exist")
                }
                paths.append(path)
            case .glob(let folder, let prefix):
                guard let names = try? manager.contentsOfDirectory(atPath: root.appending(path: folder).path) else {
                    throw Failure("\(folder) is an input but does not exist")
                }
                let matched = names.filter { $0.hasPrefix(prefix) && $0.hasSuffix(".swift") }
                guard !matched.isEmpty else { throw Failure("no \(prefix)*.swift in \(folder)") }
                paths += matched.map { folder + "/" + $0 }
            case .tree(let folder):
                guard let walker = manager.enumerator(atPath: root.appending(path: folder).path) else {
                    throw Failure("\(folder) is an input but does not exist")
                }
                paths += walker.compactMap { $0 as? String }.filter { $0.hasSuffix(".swift") }.map { folder + "/" + $0 }
            }
        }
        return paths.sorted()
    }

    /// Every input file, parsed.
    public func parse() throws -> [(path: String, syntax: SourceFileSyntax)] {
        try inputFiles().map { path in
            let text = try String(contentsOf: root.appending(path: path), encoding: .utf8)
            return (path, Parser.parse(source: text))
        }
    }

    /// generated.ts, as it should be now.
    public func generate() throws -> String {
        _ = try parse()
        var out = """
        // GENERATED by Packages/WebTypes (agents-webtypes) from AgentsKitCore. Do not edit.
        // Regenerate: scripts/web.sh types
        //
        // Read from DaemonAPI*.swift, DaemonAPI+Control.swift, Grant.swift, ControlAuth.swift
        // and Model/, in Packages/AgentsKit/Sources/AgentsKitCore.

        """
        out += "\nexport {};\n"
        return out
    }
}
